# Generated by Django 4.0.3 on 2022-12-08 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engineer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sudo_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestdate', models.DateField(auto_now_add=True)),
                ('request_time', models.TimeField(auto_now_add=True, null=True)),
                ('mgr_approved_date', models.DateTimeField(auto_now=True, null=True)),
                ('cto_approved_date', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer', models.CharField(max_length=20)),
                ('bad_last_service', models.DateField()),
                ('bad_serial_number', models.CharField(max_length=20)),
                ('bad_model_number', models.CharField(max_length=20)),
                ('bad_equipment_name', models.CharField(max_length=50)),
                ('bad_equipment_rating', models.CharField(max_length=10)),
                ('bad_days_in_ops', models.CharField(max_length=10)),
                ('bad_installation_date', models.DateField()),
                ('new_equipment_name', models.CharField(max_length=100)),
                ('new_manufacturer', models.CharField(max_length=50)),
                ('new_equipment_rating', models.CharField(max_length=10)),
                ('expected_date', models.DateField()),
                ('sitemanager_comment', models.CharField(max_length=500)),
                ('hod_comment', models.CharField(max_length=500)),
                ('justification', models.CharField(max_length=3000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.items')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetRequests.site', verbose_name='Confirm Site')),
                ('site_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetRequests.engineer', verbose_name='Confirm Engineer')),
                ('site_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diesel Requests',
                'ordering': ['-requestdate'],
            },
        ),
    ]
