# Generated by Django 4.0.3 on 2022-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetRequests', '0003_alter_assetrequest_bad_days_in_ops_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetRequest',
        ),
    ]
