# Generated by Django 4.0.3 on 2022-12-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssetRequests', '0004_delete_assetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestdate', models.DateField(auto_now_add=True)),
                ('request_time', models.TimeField(auto_now_add=True, null=True)),
                ('mgr_approved_date', models.DateTimeField(auto_now=True, null=True)),
                ('cto_approved_date', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer', models.CharField(max_length=20)),
                ('bad_last_service', models.DateField(verbose_name='Last Serviced Date')),
                ('bad_serial_number', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('bad_model_number', models.CharField(max_length=20, verbose_name='Model Number')),
                ('bad_equipment_name', models.CharField(max_length=50, verbose_name='Equipment Name')),
                ('bad_equipment_rating', models.CharField(max_length=10, verbose_name='Equipment Rating')),
                ('bad_days_in_ops', models.CharField(max_length=10, verbose_name='Days/Weeks/Months in Operations')),
                ('bad_installation_date', models.DateField(verbose_name='Installed Date')),
                ('new_equipment_name', models.CharField(max_length=100, verbose_name='Equipment Name')),
                ('new_manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('new_equipment_rating', models.CharField(max_length=10, verbose_name='Rating')),
                ('expected_date', models.DateField(verbose_name='Expected Delivery Date')),
                ('sitemanager_comment', models.CharField(max_length=500, verbose_name='Site Manager Comment')),
                ('hod_comment', models.CharField(max_length=500, verbose_name='HOD/CTO Comment')),
                ('justification', models.CharField(max_length=3000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.items')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetRequests.site', verbose_name='Confirm Site')),
                ('site_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetRequests.engineer', verbose_name='Confirm Engineer')),
                ('site_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diesel Requests',
                'ordering': ['-requestdate'],
            },
        ),
    ]
