# Generated by Django 4.0.3 on 2022-12-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_number', models.CharField(max_length=12)),
                ('product', models.CharField(max_length=100)),
            ],
        ),
    ]
